<?php
    echo '<h1>Hello Phalcon</h1>';
    echo PHP_EOL;
    echo PHP_EOL;
    echo $this->tag->linkTO(
        'signup',
        'Sign Up Here!'
    );
    if ($users->count() > 0) {
        ?>
        <table class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th>#</th>
                    <th>姓名</th>
                    <th>邮箱</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="3">用户数: <?php echo $users->count()?></td>
                </tr>
            </tfoot>
            <tbody>
                <?php foreach ($users as $user) { ?>
                    <tr>
                        <td><?php echo $user->id?></td>
                        <td><?php echo $user->name?></td>
                        <td><?php echo $user->email?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
<?php
    }